services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: belkius
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: paws_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: