services:
  app:
    environment:
      - JWT_SECRET=ivanbob200613337chicherina99
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - paws-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: paws_db
      POSTGRES_USER: belkius
      POSTGRES_PASSWORD: 159753
    ports:
      - "5432:5432"
    volumes:
      - paws-db:/var/lib/postgresql/data
    networks:
      - paws-network

volumes:
  paws-db:

networks:
  paws-network: