CREATE TABLE pets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    type            VARCHAR(255),
    breed           VARCHAR(255),
    chip_number     VARCHAR(255),
    sex             SMALLINT,
    birth_date      date,
    medication      BOOLEAN                                 NOT NULL,
    age             INTEGER                                 NOT NULL,
    last_feed       TIMESTAMP WITHOUT TIME ZONE,
    last_walk       TIMESTAMP WITHOUT TIME ZONE,
    last_medication TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);